/**
 * created by gxw on 2017/3/10.
 */


// const url = 'http://tstore.ha-pi.cn/';
// const url = 'http://storebms.ha-pi.cn/';
const url = 'http://127.0.0.1/webapp/';


module.exports = {
  store_info: `${url}rest/index.php?c=istore&a=info&XDEBUG_SESSION_START=17016`,
  store_userinfo: `${url}rest/index.php?c=iuser&a=userinfo`,
  store_wait_pay: `${url}rest/index.php?c=iorder&a=wait_pay_order`,
  store_wait_receive: `${url}rest/index.php?c=iorder&a=wait_receive_order`,
  wechat_login: `${url}rest/index.php?c=iuser&a=wechat_login`,
  get_pay_info: `${url}rest/index.php?c=iorder&a=pay_info`,
  category_list: `${url}rest/index.php?c=istore&a=category_list`,
  category_products: `${url}rest/index.php?c=istore&a=category_products`,
  home: `${url}rest/index.php?c=istore&a=home`,
  product_detail: `${url}rest/index.php?c=istore&a=product_detail`,
  order_detail: `${url}rest/index.php?c=iorder&a=detail`,
  add_collect: `${url}rest/index.php?c=iuser&a=add_collect`,
  cancel_collect: `${url}rest/index.php?c=iuser&a=cancel_collect`,
  store_checked_order: `${url}rest/index.php?c=iorder&a=checked_order`,
  store_back_order: `${url}rest/index.php?c=iorder&a=back_order`,
  store_close_order: `${url}rest/index.php?c=iorder&a=canceled_order`,
  store_cart_list: `${url}rest/index.php?c=iuser&a=cart_list`,
  store_cart_delete: `${url}rest/index.php?c=iuser&a=delete_cart`,
  store_cart_add: `${url}rest/index.php?c=iuser&a=add_cart`,
  store_cart_clean: `${url}rest/index.php?c=iuser&a=clean_cart`,
  store_order_detail: `${url}rest/index.php?c=iorder&a=detail`,
  store_commit_order: `${url}rest/index.php?c=iorder&a=submit`,
  address_list: `${url}rest/index.php?c=iuser&a=address_list`,
  del_address: `${url}rest/index.php?c=iuser&a=delete_address`,
  edit_address: `${url}rest/index.php?c=iuser&a=edit_address`,
  add_address: `${url}rest/index.php?c=iuser&a=add_address`,
  set_default_address: `${url}rest/index.php?c=iuser&a=set_default_address`,
  store_cancel_order: `${url}rest/index.php?c=iorder&a=cancel`,
  apply_cash: `${url}rest/index.php?c=iuser&a=apply_cash`,
  bill_list: `${url}rest/index.php?c=iuser&a=bill`,
  coupon_list: `${url}rest/index.php?c=iuser&a=coupon`,
  user_info: `${url}rest/index.php?c=iuser&a=info`,
  distribution_list: `${url}rest/index.php?c=iuser&a=collect_list`,
  delete_distribution_list: `${url}rest/index.php?c=iuser&a=delete_collect`,
  confirm_order: `${url}rest/index.php?c=iorder&a=confirm`,
  back_order: `${url}rest/index.php?c=iorder&a=back`,
  query_all: `${url}rest/index.php?c=iorder&a=all_order`,
  wait_send_order: `${url}rest/index.php?c=iorder&a=wait_send_order`,
  wechat_sign: `${url}rest/index.php?c=istore&a=getSign`,
  confirm: `${url}rest/index.php?c=iorder&a=confirm`,
  back: `${url}rest/index.php?c=iorder&a=back`,
  car_num: `${url}rest/index.php?c=istore&a=get_cart_num`,
  integral_product_list: `${url}rest/index.php?c=istore&a=integral_product_list`,
  integral_product_detail: `${url}rest/index.php?c=istore&a=integral_product_detail`,
  integral_product_exchange: `${url}rest/index.php?c=istore&a=exchange_product`,
  query_logistics: `${url}rest/index.php?c=iorder&a=get_logistics_info`,
  get_user_coupon: `${url}rest/index.php?c=iorder&a=get_user_coupon`,
  exchange_list: `${url}rest/index.php?c=iuser&a=exchange_list`,
  query_reserve: `${url}rest/index.php?c=istore&a=reserve`,
  check_login: `${url}rest/index.php?c=iuser&a=check_login`,
  verify_sms: `${url}rest/index.php?c=iuser&a=verify_sms`,
  bind_user_mobile: `${url}rest/index.php?c=iuser&a=bind_user_mobile`,
  update_user_info: `${url}rest/index.php?c=iuser&a=update_user_info&XDEBUG_SESSION_START=10413`,
  sign_send_point: `${url}rest/index.php?c=iuser&a=sign_send_point`,
  wait_comment_num: `${url}rest/index.php?c=iorder&a=wait_comment_order_num`,
  get_user_point:`${url}rest/index.php?c=iuser&a=get_user_point`,
  query_point_detail: `${url}rest/index.php?c=iuser&a=point_record`,
};
